version: '3.7'
services:
  fileservice-api:
    container_name: fileservice-api
    user: ${LOCAL_UID}:${LOCAL_GID}
    build: 
      context: ./api
      dockerfile: docker/Dockerfile-dev
    ports:
      - 8082:8082
    volumes:
      - ./api:/fileservice-api
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb-dev:/data/db
  fileservice-ui:
    container_name: fileservice-ui
    user: ${LOCAL_UID}:${LOCAL_GID}
    build: 
      context: ./fileservice-ui
      dockerfile: docker/Dockerfile-dev
    ports:
      - 8080:8080
    volumes:
      - ./fileservice-ui:/fileservice-ui

volumes:
  mongodb-dev: