version: '3.7'
services:
  xroad-drive-api:
    container_name: xroad-drive-api
    image: yamatokataoka/xroad-drive-api:1.0.0
    ports:
      - 8082:8082
    volumes:
      - files:/etc/xroad-drive/xroad-drive-api/files
    depends_on:
      - mongodb
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
  xroad-drive-ui:
    container_name: xroad-drive-ui
    image: yamatokataoka/xroad-drive-ui:1.0.0
    ports:
      - 8000:80
  xroad-security-server-standalone:
    container_name: xroad-security-server-standalone
    image: niis/xroad-security-server-standalone:bionic-6.23.0
    environment:
      - XROAD_TOKEN_PIN=secret
    ports:
      - 8080:4000
      - 8081:80

volumes:
  mongodb:
  files: