version: '3.7'
services:
  xroad-drive-api:
    container_name: xroad-drive-api
    user: ${LOCAL_UID}:${LOCAL_GID}
    build: 
      context: ./xroad-drive-api
      dockerfile: docker/Dockerfile
      target: develop
    depends_on:
      - mongodb
    ports:
      - 8082:8082
    volumes:
      - ./xroad-drive-api:/xroad-drive-api
    command: ["./gradlew", "bootRun"]
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./mongodb-dev:/data/db
  xroad-drive-ui:
    container_name: xroad-drive-ui
    user: ${LOCAL_UID}:${LOCAL_GID}
    build: 
      context: ./xroad-drive-ui
      dockerfile: docker/Dockerfile
      target: develop
    ports:
      - 8080:8080
    volumes:
      - ./xroad-drive-ui:/xroad-drive-ui
    command: ["yarn", "run", "serve"]