version: '3.7'
services:
  fileservice-api:
    container_name: fileservice-api
    build: 
      context: ./api
      dockerfile: Dockerfile-dev
    ports:
      - 8082:8082
    volumes:
      - ./api:/fileservice-api
      - files:/fileservice-api/files # exclude ./api/files
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
  fileservice-ui:
    container_name: fileservice-ui
    build: 
      context: ./fileservice-ui
      dockerfile: Dockerfile-dev
    ports:
      - 8080:8080
    volumes:
      - ./fileservice-ui:/fileservice-ui

volumes:
  files:
