version: '3.7'
services:
  fileservice-api:
    container_name: fileservice-api
    build: ./api
    ports:
      - 8082:8082
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
volumes:
  db:
